public class Address {
    public void homeAddress() {
        String myName='Ozan';
        Integer totalNumberAtHome=2;
        String houseName='NXT condos';
        Integer houseNumber=105;
        String streetName='Queensway';
        String cityName='Toronto';
        String stateName='Ontario';
        String stateIsoCode='ON';
        String countryName='Canada';
        String countryIsoCode='Ca';
        String zipCode='m6s5b5';
        Boolean currentHome=true;
        System.debug(myName+' '+totalNumberAtHome+' '+houseNumber+' '+houseName+
        ' '+streetName+' '+cityName+' '+stateName+' '+stateIsoCode+
        ' '+countryIsoCode+' '+zipCode
        +' '+currentHome);
    }
}
        