public class Player {
    public void playing() {
       String player1name='Arda';
       String player2name='Ferdi';
       String player3name='Zajc';
       String player4name='Crespo';
       String player5name='Osayi';
        system.debug(player1name);
        system.debug(player2name);
        system.debug(player3name);
        system.debug(player4name);
        system.debug(player5name);

        
    }
}
